apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  labels:
    app: postgres
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: dbport
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.database.name }}"
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.database.password }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ .Values.database.storageSize }}"