apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:{{ .Values.app.containerPort }}"]
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              value: "{{ .Values.database.user }}"
            - name: DB_PASS
              value: "{{ .Values.database.password }}"