[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_cluster]
master ansible_host=93.77.177.208
worker ansible_host=111.88.253.197

[srv]
srv_node ansible_host=111.88.247.184