[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_cluster]
master ansible_host=93.77.187.125
worker ansible_host=89.169.137.45

[srv]
srv_node ansible_host=89.169.147.14